"""empty message

Revision ID: 5b890403e46f
Revises: 897b4f16cee5
Create Date: 2020-05-10 01:47:35.045154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b890403e46f'
down_revision = '897b4f16cee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artistgeners', 'name')
    op.drop_column('venuegeners', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venuegeners', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('artistgeners', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
