"""empty message

Revision ID: 897b4f16cee5
Revises: 2404f415fcd0
Create Date: 2020-05-10 01:40:42.306918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897b4f16cee5'
down_revision = '2404f415fcd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venuegeners', sa.Column('vanue_id', sa.Integer(), nullable=False))
    op.drop_constraint('venuegeners_artist_id_fkey', 'venuegeners', type_='foreignkey')
    op.create_foreign_key(None, 'venuegeners', 'venue', ['vanue_id'], ['id'])
    op.drop_column('venuegeners', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venuegeners', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venuegeners', type_='foreignkey')
    op.create_foreign_key('venuegeners_artist_id_fkey', 'venuegeners', 'venue', ['artist_id'], ['id'])
    op.drop_column('venuegeners', 'vanue_id')
    # ### end Alembic commands ###
